"""add dual role system fields to users

Revision ID: bd0e21e15715
Revises: f9af018b19fc
Create Date: 2026-08-02 17:04:57.599803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd0e21e15715'
down_revision: Union[str, None] = 'f9af018b19fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOT NULL columns need a server_default so this works even if `users`
    # already has rows — Postgres must be able to fill in a value for them.
    op.add_column(
        'users',
        sa.Column(
            'roles',
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("ARRAY['customer']::varchar[]"),
            nullable=False,
        ),
    )
    op.add_column('users', sa.Column('customer_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('business_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column(
        'users',
        sa.Column('business_verified', sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.add_column('users', sa.Column('date_became_car_owner', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_roles'), 'users', ['roles'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_roles'), table_name='users')
    op.drop_column('users', 'date_became_car_owner')
    op.drop_column('users', 'business_verified')
    op.drop_column('users', 'business_profile')
    op.drop_column('users', 'customer_profile')
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
