"""add user_photos table

Revision ID: f654d8dc87d9
Revises: 5427f6a9c636
Create Date: 2026-08-02 19:09:07.881721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f654d8dc87d9'
down_revision: Union[str, None] = '5427f6a9c636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloudinary_public_id')
    )
    op.create_index(op.f('ix_user_photos_id'), 'user_photos', ['id'], unique=False)
    op.create_index(op.f('ix_user_photos_user_id'), 'user_photos', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_photos_user_id'), table_name='user_photos')
    op.drop_index(op.f('ix_user_photos_id'), table_name='user_photos')
    op.drop_table('user_photos')
    # ### end Alembic commands ###
